- include_vars: "{{ item }}"
  with_first_found:
    - "vars-{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version}}.yml"
    - "vars-{{ ansible_distribution | lower }}.yml"
    - "vars-{{ ansible_os_family | lower }}.yml"
  ignore_errors: yes

- include_tasks: "{{ item }}"
  with_first_found:
    - "tasks-{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version}}.yml"
    - "tasks-{{ ansible_distribution | lower }}.yml"
    - "tasks-{{ ansible_os_family | lower }}.yml"