- include_tasks: "{{ item }}"
  with_first_found:
    - "tasks-{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version}}.yml"
    - "tasks-{{ ansible_distribution | lower }}.yml"
    - "tasks-{{ ansible_os_family | lower }}.yml"